using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rook.Services.Vision.Video
{
    /// <summary>
    /// Provider-shape seam for video generation. Returns provider-side
    /// result types (<see cref="ProviderSubmitResult"/> /
    /// <see cref="ProviderStatusResult"/> / <see cref="ProviderCancelResult"/>
    /// / <see cref="ProviderFetchResult"/>) that the manager translates
    /// into the consumer-facing v3.1 D3 contract
    /// (<see cref="JobSubmitResult"/> etc.) after persistence + artifact
    /// write.
    ///
    /// Layering: the provider produces bytes, IDs, and tokens; the manager
    /// owns ArtifactStore writes, artifact-id minting, and ledger
    /// transitions. The provider never knows about Rook artifact IDs.
    ///
    /// Statelessness: providers must not cache per-job state across calls.
    /// All state needed across method invocations
    /// (<c>provider_job_id</c>, <c>provider_result_token</c>) is persisted
    /// by the manager and passed back as method arguments. This lets V1b's
    /// "no auto-resume on restart" stance hold without provider-side
    /// recovery code.
    ///
    /// All methods return result envelopes — implementations should
    /// translate provider-side errors into typed
    /// <see cref="VideoJobError"/> values rather than throwing for
    /// expected failure modes (auth, quota, validation, provider job
    /// failure). Genuine transport / cancellation exceptions still
    /// propagate as exceptions.
    /// </summary>
    public interface IVideoProvider
    {
        /// <summary>
        /// Submit a generation request. The manager pre-resolves any
        /// <see cref="VideoMediaRef"/> in the request into bytes via
        /// <see cref="IVideoMediaResolver"/>; this keeps providers
        /// independent of Rook's artifact storage layout.
        /// </summary>
        Task<ProviderSubmitResult> SubmitAsync(
            VideoGenerationRequest request,
            IReadOnlyDictionary<VideoMediaRef, ResolvedVideoMedia> resolvedMedia,
            CancellationToken ct);

        Task<ProviderStatusResult> GetStatusAsync(
            string providerJobId,
            CancellationToken ct);

        Task<ProviderCancelResult> CancelAsync(
            string providerJobId,
            CancellationToken ct);

        /// <summary>
        /// Fetch the generated bytes once provider-Complete. The manager
        /// passes both <paramref name="providerJobId"/> and
        /// <paramref name="providerResultToken"/> (persisted to the ledger
        /// when the status poll first reported provider-Complete) so the
        /// provider stays stateless. <paramref name="providerResultToken"/>
        /// may be null only if the provider can re-derive its result handle
        /// from <paramref name="providerJobId"/> alone.
        /// </summary>
        Task<ProviderFetchResult> FetchResultAsync(
            string providerJobId,
            string? providerResultToken,
            CancellationToken ct);
    }
}
