"""Operational validation and repair tooling for Rook runtimes."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

try:
    import tomllib
    TOMLDecodeError = tomllib.TOMLDecodeError
except ModuleNotFoundError:
    tomllib = None  # type: ignore[assignment]
    TOMLDecodeError = ValueError

import anyio
from mcp import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

from .runtime_paths import RuntimePaths, resolve_runtime_paths

REQUIRED_MCP_ENV_KEYS = ("PYTHONPATH", "PYTHONHOME", "ROOK_INSTALL_ROOT", "ROOK_DATA_DIR", "ROOK_MODE")
PATH_LIKE_ENV_KEYS = {"ROOK_INSTALL_ROOT", "ROOK_DATA_DIR", "CHIRP_HOME"}
MANAGED_COMPANION_RUNTIMES = ("net8.0", "net7.0", "net48")


def _managed_companion_payloads(plugin_dir: Path) -> list[tuple[str, Path]]:
    return [(runtime, plugin_dir / runtime / "Rook.rhp") for runtime in MANAGED_COMPANION_RUNTIMES]


def _normalize_path_string(value: str | Path) -> str:
    return str(value).replace("\\", "/")


def _build_expected_env(runtime_paths: RuntimePaths, chirp_home: str | None = None) -> dict[str, str]:
    env = {
        "PYTHONPATH": "",
        "PYTHONHOME": "",
        "ROOK_INSTALL_ROOT": _normalize_path_string(runtime_paths.install_root),
        "ROOK_DATA_DIR": _normalize_path_string(runtime_paths.data_root),
        "ROOK_MODE": runtime_paths.mode,
    }
    chirp_home = chirp_home if chirp_home is not None else os.environ.get("CHIRP_HOME")
    if chirp_home and Path(chirp_home).exists():
        env["CHIRP_HOME"] = _normalize_path_string(Path(chirp_home))
    return env


def _build_expected_mcp_entry(runtime_paths: RuntimePaths, python_path: str, chirp_home: str | None = None) -> dict[str, Any]:
    return {
        "type": "stdio",
        "command": _normalize_path_string(python_path),
        "args": ["-m", "rook"],
        "cwd": _normalize_path_string(runtime_paths.mcp_server_dir),
        "env": _build_expected_env(runtime_paths, chirp_home=chirp_home),
    }


def _format_toml_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _generate_codex_toml(runtime_paths: RuntimePaths, python_path: str, chirp_home: str | None = None) -> str:
    mcp_dir = _normalize_path_string(runtime_paths.mcp_server_dir)
    env_vars = _build_expected_env(runtime_paths, chirp_home=chirp_home)
    lines = [
        "# Rook MCP Server configuration for OpenAI Codex CLI",
        "# Auto-generated by Rook doctor",
        "",
        "[mcp_servers.rook]",
        f"command = {_format_toml_value(_normalize_path_string(python_path))}",
        'args = ["-m", "rook"]',
        f"cwd = {_format_toml_value(mcp_dir)}",
        "startup_timeout_sec = 30",
        "tool_timeout_sec = 120",
        "",
        "[mcp_servers.rook.env]",
    ]
    for key, value in env_vars.items():
        lines.append(f"{key} = {_format_toml_value(value)}")
    lines.append("")
    return "\n".join(lines)


def _config_targets() -> dict[str, Path]:
    return {
        "claude_user": Path.home() / ".claude.json",
        "claude_desktop": Path(os.environ.get("APPDATA", "")) / "Claude" / "claude_desktop_config.json",
        "codex": Path.home() / ".codex" / "config.toml",
        "claude_skill_root": Path.home() / ".claude" / "skills",
        "codex_skill_root": Path.home() / ".codex" / "skills",
        "legacy_claude": Path.home() / ".claude" / ".mcp.json",
    }


def _skill_source_root(runtime_paths: RuntimePaths) -> Path:
    return runtime_paths.install_root / ".claude" / "skills"


def _codex_skill_source_root(runtime_paths: RuntimePaths) -> Path:
    return runtime_paths.install_root / ".agents" / "skills"


def _should_check_claude(force: bool) -> bool:
    targets = _config_targets()
    if force:
        return True
    user_data = _read_json(targets["claude_user"]) or {}
    if "rook" in user_data.get("mcpServers", {}):
        return True
    desktop_data = _read_json(targets["claude_desktop"]) or {}
    if "rook" in desktop_data.get("mcpServers", {}):
        return True
    return targets["claude_skill_root"].exists()


def _should_check_codex(force: bool) -> bool:
    targets = _config_targets()
    if force:
        return True
    return _codex_has_rook_section(targets["codex"]) or targets["codex_skill_root"].exists()


def _read_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _validate_mcp_entry(
    actual: dict[str, Any] | None,
    runtime_paths: RuntimePaths,
    expected_python_path: str | None = None,
) -> tuple[bool, str | None]:
    if not isinstance(actual, dict):
        return False, "missing rook entry"
    if actual.get("type") != "stdio":
        return False, "entry type is not stdio"
    command = actual.get("command", "")
    if not command:
        return False, "entry command is missing"
    if not Path(command).exists():
        return False, f"registered interpreter missing: {command}"
    if expected_python_path and _normalize_path_string(command) != _normalize_path_string(expected_python_path):
        return False, f"expected command {expected_python_path}, found {command}"
    if list(actual.get("args", [])) != ["-m", "rook"]:
        return False, "entry args do not match ['-m', 'rook']"
    expected_cwd = _normalize_path_string(runtime_paths.mcp_server_dir)
    if _normalize_path_string(actual.get("cwd", "")) != expected_cwd:
        return False, f"entry cwd does not match {expected_cwd}"

    actual_env = actual.get("env", {})
    if not isinstance(actual_env, dict):
        return False, "entry env is missing"
    expected_env = _build_expected_env(runtime_paths)
    for key in REQUIRED_MCP_ENV_KEYS:
        expected_value = expected_env[key]
        actual_value = actual_env.get(key)
        if key in PATH_LIKE_ENV_KEYS:
            expected_value = _normalize_path_string(expected_value)
            actual_value = _normalize_path_string(actual_value or "")
        if actual_value != expected_value:
            return False, f"env {key} does not match expected value"
    return True, None


def _codex_has_rook_section(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = _load_codex_toml(path.read_text(encoding="utf-8"))
    except (OSError, TOMLDecodeError, ValueError):
        return False
    return "rook" in data.get("mcp_servers", {})


def _parse_toml_value(value: str) -> Any:
    value = value.strip()
    if not value:
        return ""
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        if value.isdigit():
            return int(value)
        return value


def _parse_codex_rook_toml_fallback(text: str) -> dict[str, Any]:
    """Parse the generated Codex MCP TOML subset on Python 3.10.

    Rook's public installer supports Python 3.10+, but stdlib tomllib only
    exists on Python 3.11+. The installer-generated Codex config only needs
    basic strings, integers, and string arrays under two known sections.
    """
    entry: dict[str, Any] = {}
    env: dict[str, Any] = {}
    section: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("["):
            if not line.endswith("]"):
                raise ValueError(f"invalid TOML section header: {line}")
            section = line[1:-1].strip()
            continue
        if section not in {"mcp_servers.rook", "mcp_servers.rook.env"}:
            continue
        if "=" not in line:
            raise ValueError(f"invalid TOML assignment: {line}")
        key, raw_value = line.split("=", 1)
        target = env if section == "mcp_servers.rook.env" else entry
        target[key.strip()] = _parse_toml_value(raw_value)
    if env:
        entry["env"] = env
    return {"mcp_servers": {"rook": entry}}


def _load_codex_toml(text: str) -> dict[str, Any]:
    if tomllib is not None:
        return tomllib.loads(text)
    return _parse_codex_rook_toml_fallback(text)


def _validate_codex_config(
    path: Path,
    runtime_paths: RuntimePaths,
    expected_python_path: str | None = None,
) -> tuple[bool, str | None]:
    if not path.exists():
        return False, "config file is missing"
    try:
        data = _load_codex_toml(path.read_text(encoding="utf-8"))
    except (OSError, TOMLDecodeError, ValueError) as exc:
        return False, f"invalid TOML: {exc}"

    rook = data.get("mcp_servers", {}).get("rook")
    if not isinstance(rook, dict):
        return False, "missing [mcp_servers.rook] section"

    command = rook.get("command", "")
    if not command:
        return False, "command is missing"
    if not Path(command).exists():
        return False, f"registered interpreter missing: {command}"
    if expected_python_path and _normalize_path_string(command) != _normalize_path_string(expected_python_path):
        return False, f"expected command {expected_python_path}, found {command}"
    if list(rook.get("args", [])) != ["-m", "rook"]:
        return False, "args do not match ['-m', 'rook']"
    if _normalize_path_string(rook.get("cwd", "")) != _normalize_path_string(runtime_paths.mcp_server_dir):
        return False, "cwd does not match runtime mcp_server_dir"

    env = rook.get("env", {})
    if not isinstance(env, dict):
        return False, "env table is missing"
    expected_env = _build_expected_env(runtime_paths)
    for key in REQUIRED_MCP_ENV_KEYS:
        actual_value = env.get(key)
        expected_value = expected_env[key]
        if key in PATH_LIKE_ENV_KEYS:
            actual_value = _normalize_path_string(actual_value or "")
            expected_value = _normalize_path_string(expected_value)
        if actual_value != expected_value:
            return False, f"env {key} does not match expected value"
    return True, None


def _upsert_toml_section(content: str, header: str, section_body: str) -> str:
    lines = content.splitlines()
    header_line = header.strip()
    start_idx: int | None = None
    end_idx = len(lines)
    for idx, line in enumerate(lines):
        if line.strip() == header_line:
            start_idx = idx
            break
    if start_idx is None:
        suffix = "" if not content or content.endswith("\n") else "\n"
        return content + suffix + "\n" + section_body.strip() + "\n"

    for idx in range(start_idx + 1, len(lines)):
        stripped = lines[idx].strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if not stripped.startswith(header_line.rstrip("]") + "."):
                end_idx = idx
                break

    replacement = section_body.strip().splitlines()
    updated_lines = lines[:start_idx] + replacement + lines[end_idx:]
    return "\n".join(updated_lines).rstrip() + "\n"


def _write_claude_user_config(runtime_paths: RuntimePaths, python_path: str, chirp_home: str | None = None) -> Path:
    target = _config_targets()["claude_user"]
    existing = _read_json(target) or {}
    existing.setdefault("mcpServers", {})
    existing["mcpServers"]["rook"] = _build_expected_mcp_entry(runtime_paths, python_path, chirp_home=chirp_home)
    target.write_text(json.dumps(existing, indent=2), encoding="utf-8")
    return target


def _write_claude_desktop_config(runtime_paths: RuntimePaths, python_path: str, chirp_home: str | None = None) -> Path | None:
    target = _config_targets()["claude_desktop"]
    if not target.parent.exists():
        return None
    existing = _read_json(target) or {}
    existing.setdefault("mcpServers", {})
    existing["mcpServers"]["rook"] = _build_expected_mcp_entry(runtime_paths, python_path, chirp_home=chirp_home)
    target.write_text(json.dumps(existing, indent=2), encoding="utf-8")
    return target


def _write_codex_config(runtime_paths: RuntimePaths, python_path: str, chirp_home: str | None = None) -> Path:
    target = _config_targets()["codex"]
    target.parent.mkdir(parents=True, exist_ok=True)
    rook_block = _generate_codex_toml(runtime_paths, python_path, chirp_home=chirp_home).strip()
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        target.write_text(_upsert_toml_section(existing, "[mcp_servers.rook]", rook_block), encoding="utf-8")
    else:
        target.write_text(rook_block + "\n", encoding="utf-8")
    return target


def _copy_skill_tree(source_root: Path, target_root: Path) -> bool:
    if not source_root.exists():
        return False
    target_root.mkdir(parents=True, exist_ok=True)
    for child in source_root.iterdir():
        destination = target_root / child.name
        if child.is_dir():
            shutil.copytree(child, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(child, destination)
    return True


def _skill_sentinel(root: Path) -> Path:
    return root / "design-grasshopper" / "SKILL.md"


@dataclass
class DoctorCheck:
    name: str
    ok: bool
    detail: str | None = None
    severity: str = "error"
    value: Any = None


@dataclass
class DoctorResult:
    ok: bool
    runtime: dict[str, Any]
    checks: list[DoctorCheck] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    fixes_applied: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "runtime": self.runtime,
            "checks": [asdict(check) for check in self.checks],
            "warnings": self.warnings,
            "fixes_applied": self.fixes_applied,
        }


async def _probe_mcp(runtime_paths: RuntimePaths, python_path: str) -> dict[str, Any]:
    env = os.environ.copy()
    expected_env = _build_expected_env(runtime_paths)
    env.update(expected_env)

    server = _build_probe_server_parameters(runtime_paths, python_path, env=env)
    t0 = time.perf_counter()
    with _probe_stderr_buffer() as stderr_buffer:
        with anyio.fail_after(30):
            async with stdio_client(server, errlog=stderr_buffer) as (read_stream, write_stream):
                async with ClientSession(read_stream, write_stream) as session:
                    initialize_result = await session.initialize()
                    tools_result = await session.list_tools()
        stderr_buffer.seek(0)
        stderr_text = stderr_buffer.read()
    elapsed = time.perf_counter() - t0
    return {
        "elapsed_seconds": elapsed,
        "server_name": initialize_result.serverInfo.name,
        "tool_count": len(tools_result.tools),
        "stderr": stderr_text,
    }


def _build_probe_server_parameters(
    runtime_paths: RuntimePaths,
    python_path: str,
    *,
    env: dict[str, str] | None = None,
) -> StdioServerParameters:
    return StdioServerParameters(
        command=python_path,
        args=["-m", "rook"],
        env=env,
        cwd=str(runtime_paths.mcp_server_dir),
        encoding_error_handler="replace",
    )


def _probe_stderr_buffer():
    return tempfile.TemporaryFile(mode="w+", encoding="utf-8", errors="replace")


def _run_handshake_checks(runtime_paths: RuntimePaths, python_path: str) -> list[DoctorCheck]:
    cold = anyio.run(_probe_mcp, runtime_paths, python_path)
    warm = anyio.run(_probe_mcp, runtime_paths, python_path)

    checks = [
        DoctorCheck(
            name="MCP initialize + list_tools (cold)",
            ok=(
                cold["server_name"] == "rook"
                and cold["tool_count"] > 0
                and cold["elapsed_seconds"] <= 3.0
            ),
            detail=f"server={cold['server_name']} tools={cold['tool_count']}",
            value=round(cold["elapsed_seconds"], 3),
        ),
        DoctorCheck(
            name="MCP initialize + list_tools (warm)",
            ok=(
                warm["server_name"] == "rook"
                and warm["tool_count"] > 0
                and warm["elapsed_seconds"] <= 1.0
            ),
            detail=f"server={warm['server_name']} tools={warm['tool_count']}",
            value=round(warm["elapsed_seconds"], 3),
        ),
    ]
    return checks


def run_doctor(
    *,
    fix: bool = False,
    check_claude: bool = False,
    check_codex: bool = False,
    check_plugins: bool = False,
    skip_handshake: bool = False,
    expected_python_path: str | None = None,
) -> DoctorResult:
    runtime_paths = resolve_runtime_paths()
    python_path = expected_python_path or sys.executable
    targets = _config_targets()

    if runtime_paths.mode != "dev":
        check_claude = _should_check_claude(check_claude)
        check_codex = _should_check_codex(check_codex)

    result = DoctorResult(
        ok=True,
        runtime={
            "mode": runtime_paths.mode,
            "install_root": str(runtime_paths.install_root),
            "data_root": str(runtime_paths.data_root),
            "logs_root": str(runtime_paths.logs_root),
            "mcp_server_dir": str(runtime_paths.mcp_server_dir),
            "python": python_path,
        },
    )

    if fix:
        claude_source_root = _skill_source_root(runtime_paths)
        codex_source_root = _codex_skill_source_root(runtime_paths)
        chirp_home = os.environ.get("CHIRP_HOME")
        if check_claude:
            try:
                fixed_path = _write_claude_user_config(runtime_paths, python_path, chirp_home=chirp_home)
                result.fixes_applied.append(f"updated {fixed_path}")
                desktop_fixed = _write_claude_desktop_config(runtime_paths, python_path, chirp_home=chirp_home)
                if desktop_fixed is not None:
                    result.fixes_applied.append(f"updated {desktop_fixed}")
                if _copy_skill_tree(claude_source_root, targets["claude_skill_root"]):
                    result.fixes_applied.append(f"synced {targets['claude_skill_root']}")
            except Exception as exc:
                result.checks.append(
                    DoctorCheck(name="--fix Claude integration", ok=False, detail=str(exc), severity="warning")
                )
        if check_codex:
            try:
                fixed_path = _write_codex_config(runtime_paths, python_path, chirp_home=chirp_home)
                result.fixes_applied.append(f"updated {fixed_path}")
                if _copy_skill_tree(codex_source_root, targets["codex_skill_root"]):
                    result.fixes_applied.append(f"synced {targets['codex_skill_root']}")
            except Exception as exc:
                result.checks.append(
                    DoctorCheck(name="--fix Codex integration", ok=False, detail=str(exc), severity="warning")
                )

    result.checks.append(
        DoctorCheck(
            name="Target interpreter exists",
            ok=Path(python_path).exists(),
            value=python_path,
        )
    )

    try:
        import_result = subprocess.run(
            [python_path, "-c", "import rook; print('ok')"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        result.checks.append(
            DoctorCheck(
                name="import rook",
                ok=import_result.returncode == 0 and import_result.stdout.strip().endswith("ok"),
                detail=import_result.stderr.strip() if import_result.returncode != 0 else None,
            )
        )
    except Exception as exc:
        result.checks.append(DoctorCheck(name="import rook", ok=False, detail=str(exc)))

    runtime_paths.data_root.mkdir(parents=True, exist_ok=True)
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=runtime_paths.data_root,
            prefix="rook-doctor-",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write("ok")
            temp_path = Path(handle.name)
        temp_path.unlink(missing_ok=True)
        result.checks.append(
            DoctorCheck(
                name="ROOK_DATA_DIR writable",
                ok=True,
                value=str(runtime_paths.data_root),
            )
        )
    except Exception as exc:
        result.checks.append(
            DoctorCheck(
                name="ROOK_DATA_DIR writable",
                ok=False,
                detail=str(exc),
                value=str(runtime_paths.data_root),
            )
        )

    if check_claude:
        user_data = _read_json(targets["claude_user"])
        user_entry = (user_data or {}).get("mcpServers", {}).get("rook")
        user_ok, user_detail = _validate_mcp_entry(user_entry, runtime_paths, expected_python_path=expected_python_path)
        result.checks.append(
            DoctorCheck(
                name="Claude Code config",
                ok=user_ok,
                detail=user_detail,
                value=str(targets["claude_user"]),
            )
        )

        desktop_data = _read_json(targets["claude_desktop"])
        desktop_entry = (desktop_data or {}).get("mcpServers", {}).get("rook")
        if desktop_entry is not None or targets["claude_desktop"].exists() or targets["claude_desktop"].parent.exists():
            desktop_ok, desktop_detail = _validate_mcp_entry(
                desktop_entry,
                runtime_paths,
                expected_python_path=expected_python_path,
            )
            result.checks.append(
                DoctorCheck(
                    name="Claude Desktop config",
                    ok=desktop_ok,
                    detail=desktop_detail,
                    value=str(targets["claude_desktop"]),
                )
            )

        result.checks.append(
            DoctorCheck(
                name="Claude skills installed",
                ok=_skill_sentinel(targets["claude_skill_root"]).exists(),
                value=str(targets["claude_skill_root"]),
            )
        )

    if check_codex:
        codex_ok, codex_detail = _validate_codex_config(
            targets["codex"],
            runtime_paths,
            expected_python_path=expected_python_path,
        )
        result.checks.append(
            DoctorCheck(
                name="Codex config",
                ok=codex_ok,
                detail=codex_detail,
                value=str(targets["codex"]),
            )
        )
        result.checks.append(
            DoctorCheck(
                name="Codex skills installed",
                ok=_skill_sentinel(targets["codex_skill_root"]).exists(),
                value=str(targets["codex_skill_root"]),
            )
        )

    if check_plugins:
        plugin_dir = Path(os.environ.get("APPDATA", "")) / "McNeel" / "Rhinoceros" / "8.0" / "Plug-ins" / "RookNative"
        result.checks.append(
            DoctorCheck(
                name="RookNative.rhp deployed",
                ok=(plugin_dir / "RookNative.rhp").exists(),
                value=str(plugin_dir / "RookNative.rhp"),
            )
        )
        for runtime, companion in _managed_companion_payloads(plugin_dir):
            result.checks.append(
                DoctorCheck(
                    name=f"Rook.rhp {runtime} deployed",
                    ok=companion.exists(),
                    value=str(companion),
                )
            )

    if targets["legacy_claude"].exists():
        result.warnings.append(f"Legacy Claude MCP path still exists: {targets['legacy_claude']}")

    if not skip_handshake:
        try:
            result.checks.extend(_run_handshake_checks(runtime_paths, python_path))
        except Exception as exc:
            result.checks.append(
                DoctorCheck(
                    name="MCP initialize + list_tools",
                    ok=False,
                    detail=str(exc),
                )
            )

    result.ok = all(check.ok for check in result.checks if check.severity == "error")
    return result


def _print_human(result: DoctorResult) -> None:
    print("Rook Doctor")
    print("=" * 40)
    print(f"Mode:         {result.runtime['mode']}")
    print(f"Interpreter:  {result.runtime['python']}")
    print(f"Install root: {result.runtime['install_root']}")
    print(f"Data root:    {result.runtime['data_root']}")
    print("")
    for check in result.checks:
        status = "OK" if check.ok else "FAIL"
        suffix = f" ({check.value})" if check.value is not None else ""
        print(f"[{status}] {check.name}{suffix}")
        if check.detail and not check.ok:
            print(f"  {check.detail}")
    for warning in result.warnings:
        print(f"[WARN] {warning}")
    for fix in result.fixes_applied:
        print(f"[FIXED] {fix}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate and repair the active Rook runtime.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON output.")
    parser.add_argument("--fix", action="store_true", help="Rewrite config entries and resync skills where possible.")
    parser.add_argument("--claude", action="store_true", help="Force Claude config and skill checks.")
    parser.add_argument("--codex", action="store_true", help="Force Codex config and skill checks.")
    parser.add_argument("--plugins", action="store_true", help="Check Rhino plugin deployment.")
    parser.add_argument("--python-path", help="Expected interpreter path for exact config validation.")
    parser.add_argument("--skip-handshake", action="store_true", help="Skip the MCP initialize + list_tools probe.")
    args = parser.parse_args(argv)

    result = run_doctor(
        fix=args.fix,
        check_claude=args.claude,
        check_codex=args.codex,
        check_plugins=args.plugins,
        skip_handshake=args.skip_handshake,
        expected_python_path=args.python_path,
    )

    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        _print_human(result)
    return 0 if result.ok else 1


if __name__ == "__main__":
    sys.exit(main())
