"""Regression tests for the Windows installer post-install helper."""

from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path


def load_post_install():
    repo_root = Path(__file__).resolve().parents[2]
    script_path = repo_root / "installer" / "post_install.py"
    spec = importlib.util.spec_from_file_location("rook_post_install", script_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_mcp_install_timeout_is_long_enough_for_cold_pip_installs() -> None:
    post_install = load_post_install()

    assert post_install._pip_install_timeout_seconds() >= 1800


def test_install_mcp_server_reports_timeout_repair_without_traceback(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    post_install = load_post_install()
    runtime_root = tmp_path / "runtime"
    mcp_server_dir = tmp_path / "app" / "mcp_server"
    mcp_server_dir.mkdir(parents=True)

    venv_python = runtime_root / "venv" / "Scripts" / "python.exe"
    venv_python.parent.mkdir(parents=True)
    venv_python.write_text("", encoding="utf-8")

    def fail_if_legacy_run_is_used(*args, **kwargs):
        raise subprocess.TimeoutExpired(cmd=args[0], timeout=300)

    def fake_streaming_command(*args, **kwargs):
        return 124, True

    monkeypatch.setattr(post_install.subprocess, "run", fail_if_legacy_run_is_used)
    monkeypatch.setattr(post_install, "_run_streaming_command", fake_streaming_command, raising=False)

    result = post_install.install_mcp_server(mcp_server_dir, runtime_root)

    assert result is None
    output = capsys.readouterr().out
    assert "timed out" in output
    assert "Repair command" in output
    assert "pip install -e" in output


def test_configure_codex_removes_orphaned_rook_comments(
    tmp_path: Path,
    monkeypatch,
) -> None:
    post_install = load_post_install()
    monkeypatch.setattr(post_install.Path, "home", staticmethod(lambda: tmp_path))

    codex_dir = tmp_path / ".codex"
    codex_dir.mkdir()
    config = codex_dir / "config.toml"
    config.write_text(
        "\n".join(
            [
                'model = "gpt-5-codex"',
                "",
                "# Rook MCP Server configuration for OpenAI Codex CLI",
                "# Auto-generated by Rook installer",
                "",
                "# Rook MCP Server configuration for OpenAI Codex CLI",
                "# Auto-generated by Rook installer",
                "",
            ]
        ),
        encoding="utf-8",
    )

    assert post_install.configure_codex(
        tmp_path / "app",
        tmp_path / "data",
        str(tmp_path / "runtime" / "venv" / "Scripts" / "python.exe"),
        tmp_path / "app" / "mcp_server",
    )

    content = config.read_text(encoding="utf-8")
    assert content.count("# Auto-generated by Rook installer") == 1
    assert content.count("[mcp_servers.rook]") == 1
    assert 'model = "gpt-5-codex"' in content
